### ISSUE TITLE
Doesn't build on clang-3.8

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot-lint#15]
```
[ 18%] Building CXX object CMakeFiles/colobot-lint.dir/Generators/DependencyGraphGenerator.cpp.o
/home/krzys_h/colobot-lint/Generators/DependencyGraphGenerator.cpp: In constructor ‘DependencyGraphGenerator::DependencyGraphGenerator(Context&)’:
/home/krzys_h/colobot-lint/Generators/DependencyGraphGenerator.cpp:13:122: error: ‘methodDecl’ was not declared in this scope
       m_memberCallExprMatcher(memberCallExpr(hasAncestor(methodDecl(hasDeclContext(recordDecl().bind("callerRecordDecl"))))).bind("memberCallExpr"))
                                                                                                                          ^
/home/krzys_h/colobot-lint/Generators/DependencyGraphGenerator.cpp:13:124: error: ‘memberCallExpr’ was not declared in this scope
       m_memberCallExprMatcher(memberCallExpr(hasAncestor(methodDecl(hasDeclContext(recordDecl().bind("callerRecordDecl"))))).bind("memberCallExpr"))
                                                                                                                            ^
CMakeFiles/colobot-lint.dir/build.make:182: polecenia dla obiektu 'CMakeFiles/colobot-lint.dir/Generators/DependencyGraphGenerator.cpp.o' nie powiodły się
```
